apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/product-deployment.yml
  - k8s/product-service.yml

images:
  - name: karthiq18/product-service
    newTag: latest