apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/user-deployment.yml
  - k8s/user-service.yml
  - k8s/configmap.yml

images:
  - name: karthiq18/user-service
    newTag: latest
