apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd

  annotations:
    # 🔥 Image updater config
    argocd-image-updater.argoproj.io/image-list: user-service=karthiq18/user-service
    argocd-image-updater.argoproj.io/user-service.update-strategy: newest-build

    # 🔥 Git write-back
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-credentials: secret:argocd/git-creds

spec:
  project: default

  source:
    repoURL: https://github.com/KartheekMarabathula/Multi-service-project.git
    targetRevision: main
    path: deploy/user-service

  destination:
    server: https://kubernetes.default.svc
    namespace: multi-service

  syncPolicy:
    automated:
      prune: true
      selfHeal: true