apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/KartheekMarabathula/Multi-service-project.git
    targetRevision: main
    path: deploy/user-service

  destination:
    server: https://kubernetes.default.svc
    namespace: multi-service

  syncPolicy:
    automated:
      prune: true
      selfHeal: true