apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: user-service-updater
  namespace: argocd

spec:
  applicationRefs:
    - namePattern: "user-service"

      images:
        - alias: "user-service"
          imageName: "karthiq18/user-service"

      commonUpdateSettings:
        updateStrategy: newest-build

  writeBackConfig:
    method: git
    gitConfig:
      branch: main