name: Order Service CI
on:
  push:
    branches:
      - main
    # Add your path back once you confirm the name is 100% correct
    paths:
    - 'services/order-service/**' 
    paths-ignore:
    - 'deploy/**'      # IGNORE when ArgoCD updates the manifest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/order-service:${{ github.sha }} ./services/order-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/order-service:${{ github.sha }}